### PR TITLE
Initial re-arranging for R package

### LINKED ISSUE #1: Create R package
Hi @josephbrehm and @dylanbeaudette!

I appreciate all the great work that has been done here to retrieve logic from NASIS and emulate behavior for some important interpretations! I excited to use this.

Are there plans to incorporate the latest codebase into an R package? 

It would be really handy to be able to manage dependencies, unit tests for these new functions and expected behavior, etc. through that format. I would be happy to submit a pull request with some suggested new structure and setup necessary files to get the process started.

### PR DESCRIPTION
**Pull request by brownag**
Here is some setup, Roxygen documentation, re-arranging of directories, dealing with dependencies and setup of internal datasets as individual R package data sets. 

Since "interpretation-engine" is not a valid CRAN package name, I have gone with titlecase : InterpretationEngine

All functions in local-functions.R have a bare minimum of documentation to pass R CMD check, but need TLC to be useful to those not familiar with the API.

This has not set up the various demos to use the utilities in the new package structure, but that is the logical next step -- probably first going back to the old examples from the README etc to verify all is good then incrementally work through the datasets / trees set up by @josephbrehm 

Closes #1

### CODE REVIEW

**Comment by brownag** [comment]
I have Joe’s demo working exactly as it was presented the other day using the demo data and the new R package set up and passing R CMD check.

This allows the main methods e.g. `hsg_calc`, `svi_calc` to be called from the {InterpretationEngine} namespace. Also the cached NASIS data objects are stored as a datasets within the package.

Any of you should now be able to install the package using my branch. This may take moment because remotes::install_github will clone the whole repo, even folders that are ignored by R CMD build.
```
remotes::install_github('ncss-tech/interpretation-engine@createRpackage')
```
Next will be to clean up the stub documentation I added and develop unit tests for all the main functions. 
It would be good to think about the long-term plans for storing the bricks of sample input data and further generalizing the workflows that make all those inputs so they can work on a variety of input sources.
I would agree w/ Dylan that we shouldn’t be adding more in the way of larger datasets to this repo. Small, self-contained ones to verify the algorithms are working correctly would be worth adding to the actual package – but these would be small areal extent.

**Review by dylanbeaudette — APPROVED** [review]
Spot check on the code I am familiar with. Looks good. Will test via local install later tonight.

**Comment by brownag** [comment]
For what it is worth, Utah demo verified to work on my home machine! I am running NASIS interps from home on Linux, unencumbered by real-time scanning. Woo!

**Comment by dylanbeaudette** [comment]
Installs fine on my machine. Feel free to merge after latest updates from Joe. Thanks!

**Pull request merged**
